name: Test

# triggers on
on: [push]

jobs:
  test:
    env:
      RAILS_ENV: test
      NODE_ENV: test
    runs-on: ubuntu-latest # runner - the 'virtual machine' provided by GitHub to run the workflow
    services:
      # Label used to access the service container - points to database.github.yml
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository # copies repo in runner
        uses: actions/checkout@v2 # short for https://github.com/actions/checkout
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1 # short for https://github.com/ruby/setup-ruby - sets up the ruby version based on .ruby_version
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Get Yarn cache directory path
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Setup cache key and directory for node_modules cache # next time it runs the action, it doesn't have to build all the node dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Prepare DB
        run: | # pipe adds line breaks
          cp config/database.github.yml config/database.yml
          bundle exec rails db:create db:migrate
      - name: Run model tests
        run: bundle exec test
      - name: Run system tests
        run: bundle exec rails test:system
